export const CHECKOUT_TEXTS: {
    title: string;
    empty: string;
    goToProducts: string;
    continueShopping: string;
    orderSummary: string;
    remove: string;
    subtotal: string;
    shipping: string;
    totalTaxIncluded: string;
    taxIncludedLinePrefix: string; // "（消費税"
    taxIncludedLineSuffix: string; // "を含む）"
    calculating: string;
    promoApproval: string;
    paymentMethod: string;
    stripeKeyMissing: string;
    cardOrGooglePay: string;
    walletHint: string;
    payNow: string;
    paying: string;
    paymentLoading: string;
    shippingRequiredToPay: string;
    enterAddressForShipping: string;
    billing: string;
    autofillPrevious: string;
    name: string;
    email: string;
    phone: string;
    postalCode: string;
    prefecture: string;
    city: string;
    addressLine: string;
    domesticShippingOnly: string;
    searchingAddress: string;
    selectAddressCandidate: string;
    giftNoInvoice: string;
    memo: string;
    memoPlaceholder: string;
    shipToDifferent: string;
    shippingAddress: string;
    recipientName: string;
    recipientPhone: string;
    recipientPostalCode: string;
    paymentInitFailed: string;
    addressNotFound: string;
    addressLookupFailed: string;
    paymentElementAlert: string;
    paymentFailed: string;
    statusCheckFailed: string;
    emailSendFailed: string;
    paymentProcessingError: string;
    qtyDecrease: string;
    qtyIncrease: string;
    freeShipping: string;
    freeShippingRemainPrefix: string;
    freeShippingRemain: string;
    couponLabel: string;
    couponPlaceholder: string;
    couponInvalid: string;
    couponApplied: string;
} = {
    title: "購入手続き",
    empty: "カートに商品がありません。",
    goToProducts: "商品一覧へ",
    continueShopping: "買い物を続ける",
    orderSummary: "注文内容",
    remove: "削除",
    subtotal: "小計",
    shipping: "送料",
    totalTaxIncluded: "合計（税込）",
    taxIncludedLinePrefix: "（消費税",
    taxIncludedLineSuffix: "を含む）",
    calculating: "計算中",
    promoApproval: "藤八茶寮からのお得な情報を受け取る",
    paymentMethod: "支払い方法",
    stripeKeyMissing:
      "Stripeの公開鍵が未設定です（`NEXT_PUBLIC_STRIPE_PUBLIC_KEY`）。`.env.local` を設定して再起動してください。",
    cardOrGooglePay: "クレジットカード",
    walletHint: "",
    payNow: "購入を確定する",
    paying: "決済処理中...",
    paymentLoading: "支払い方法を読み込み中…",
    shippingRequiredToPay: "送料を計算するため、まず郵便番号・住所を入力してください。",
    enterAddressForShipping: "上のフォームにお届け先住所を入力すると、送料を計算したうえでクレジットカード決済が行えます。",
    billing: "請求先",
    autofillPrevious: "前回の情報を自動入力",
    name: "お名前",
    email: "メールアドレス",
    phone: "電話番号",
    postalCode: "郵便番号",
    prefecture: "都道府県",
    city: "市区町村",
    addressLine: "住所（番地・建物名など）",
    domesticShippingOnly: "配送は日本国内のみです。海外への発送はできません。",
    searchingAddress: "住所を検索中...",
    selectAddressCandidate: "住所の候補を選択してください",
    giftNoInvoice: "金額記載の明細書は不要",
    memo: "注文に関するメモ",
    memoPlaceholder: "ご要望などがございましたらご記入ください",
    shipToDifferent: "別の住所へ配送しますか？",
    shippingAddress: "送付先",
    recipientName: "氏名",
    recipientPhone: "電話番号",
    recipientPostalCode: "〒（郵便番号）",
    paymentInitFailed: "支払い情報の初期化に失敗しました。",
    addressNotFound: "住所が見つかりませんでした",
    addressLookupFailed: "住所の取得に失敗しました",
    paymentElementAlert: "支払い方法のブロックから決済してください。",
    paymentFailed: "決済に失敗しました。",
    statusCheckFailed: "決済は完了しましたが、状態の確認に失敗しました。",
    emailSendFailed: "決済は完了しましたが、注文メール送信に失敗しました。",
    paymentProcessingError: "決済処理中にエラーが発生しました。",
    qtyDecrease: "数量を減らす",
    qtyIncrease: "数量を増やす",
    freeShipping: "送料無料です",
    freeShippingRemainPrefix: "あと ",
    freeShippingRemain: " のお買い上げで送料無料です",
    couponLabel: "クーポンコード",
    couponPlaceholder: "6～8文字のコード",
    couponInvalid: "クーポンコードはお使いになれません。",
    couponApplied: "クーポンが適用されました。",
};

