/** 共通UI文言（ナビ・カート・お問い合わせ・フッター・ページネーション等） */
export const COMMON_TEXTS = {
  nav: {
    top: "トップページ",
    products: "商品一覧",
    about: "藤八茶寮について",
    isecha: "伊勢茶とは",
    isechaBooks: "伊勢茶の本",
    isechaAmerica: "伊勢茶とアメリカ",
    isechaHowToBrew: "おいしいお茶の淹れ方",
    isechaMaccha: "抹茶とパウダー緑茶",
    isechaCaffeine: "お茶とカフェイン",
    isechaCatechin: "お茶とコレステロール",
    isechaFukamushi: "深蒸し茶について",
    isechaDecaf: "カフェインカット緑茶",
    isechaHoujicha: "ほうじ茶について",
    isechaWakocha: "和紅茶について",
    howToBrew: "お茶の淹れ方",
    userGuide: "ご注文の流れ",
    notice: "お知らせ",
    wholesale: "パートナー募集",
  },
  header: { checkout: "購入手続きへ", inquiry: "お問い合わせ" },
  floatingCheckout: "購入手続きへ",
  footer: {
    privacyPolicy: "プライバシーポリシー",
    legal: "特定商取引法に基づく表記",
    domesticShippingNote: "配送は日本国内のみです",
    address: "〒220-0072 横浜市西区浅間町1丁目4番3号ウィザードビル402",
    copyright: "©︎ 藤八茶寮 / シングルオリジン伊勢茶 108teaworks",
  },
  pagination: { prev: "前へ", next: "次へ", noticeAria: "お知らせのページネーション" },
  notice: { title: "お知らせ", empty: "現在、お知らせはありません。", backToList: "← お知らせ一覧へ" },
  product: { taxIncluded: "(税込)", productCode: "商品コード", janCode: "JANコード", relatedProducts: "関連商品", viewDetails: "詳しく見る >>", quantity: "数量", addToCart: "カートに追加", buyNow: "今すぐ買う", shipRankPre: "この商品の", shipRankLink: "配送ポイント", shipRankMid: "は", shipRankSuffix: "です", shipRankDetail: "ポイントの合計が6.0以下の場合は、クリックポスト ¥380 で、6.0を超える場合は、60サイズ ¥880 でお送りします", shipRankFree: "お買い上げ¥10,000以上で送料無料となります", shipRankTooltip: "商品ごとに設定された配送サイズの目安です。カート内の合計が6.0以下なら小型便（¥380）、6.0を超えると宅配便（¥880）でお届けします。" },
  aria: { mainMenu: "メインメニュー", menuButton: "メニュー" },
  couponBanner: "",
  cart: {
    title: "ショッピングカート",
    empty: "カートに商品はありません。",
    continueShopping: "買い物を続ける",
    taxIncluded: "（税込）",
    subtotal: "小計",
    shipping: "送料",
    shippingCalculating: "計算中",
    total: "合計（税込）",
    taxNote: "（消費税",
    taxNoteSuffix: "を含む）",
    proceedToCheckout: "購入手続きに進む",
    freeShipping: "送料無料です",
    freeShippingRemainPrefix: "あと ",
    freeShippingRemain: " のお買い上げで送料無料です",
    shippingFreeShort: "無料",
    decreaseQty: "数量を減らす",
    increaseQty: "数量を増やす",
    remove: "削除",
  },
};
