export const INQUIRY_TEXTS = {
  heading: "お問い合わせ",
  intro:
    "商品や伊勢茶に関するご質問、業務用・卸売りのご相談、イベント出店のご依頼などがございましたら、下記フォームよりお気軽にお送りください。",
  name: "お名前",
  email: "Eメール",
  message: "メッセージ",
  required: "（必須）",
  errName: "お名前を入力してください。",
  errEmail: "Eメールアドレスを入力してください。",
  errEmailInvalid: "Eメールアドレスの形式が正しくありません。",
  errMessage: "メッセージを入力してください。",
  emailNote: "",
  confirmButton: "確認する",
  confirmIntro: "入力内容をご確認ください。修正する場合は「戻る」を、送信する場合は「送信する」を押してください。",
  nameLabel: "お名前",
  emailLabel: "Eメール",
  messageLabel: "メッセージ",
  back: "戻る",
  submit: "送信する",
  sending: "送信中...",
  sendError: "送信中にエラーが発生しました。お手数ですが、時間をおいて再度お試しください。",
  doneTitle: "お問い合わせ送信完了",
  doneThanks: "お問い合わせありがとうございます。",
  doneNote:
    "内容を確認のうえ、通常2〜3営業日以内にご返信させていただきます。しばらく経っても返信が届かない場合は、迷惑メールフォルダをご確認いただくか、別のメールアドレスにて再度お問い合わせください。",
};
