export const PROMO_VIDEO_TEXTS = {
  sectionAria: "ほうじ茶ラテ動画",
  playAria: "ほうじ茶ラテの動画を再生",
  thumbAlt: "ほうじ茶ラテの動画",
  prefix: "外苑前 ",
  cafeName: "カフェ 柔和 (にゅうわ)",
  cafeNameShort: "カフェ 柔和",
  ownerIntro: "のオーナーでインフルエンサーの",
  mid: "さんが、藤八茶寮の",
  afterProduct: "を使って、とっても楽しいほうじ茶ラテを作ってくれました。ぜひご覧ください。もちろん、",
  end: "でもお楽しみいただけます。",
  productLink: "/ise-cha/houjicha-powder-80g",
  productName: "ほうじ茶パウダー",
  watchCta: "動画を見る",
  dialogAria: "ほうじ茶ラテ動画",
  closeAria: "閉じる",
};
